version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: /run/secrets/db_user
      POSTGRES_PASSWORD: /run/secrets/db_password
      POSTGRES_DB: library_db
    secrets:
      - db_user
      - db_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER_FILE}:${POSTGRES_PASSWORD_FILE}@db:5432/library_db"
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: HS256services
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
volumes:
  postgres_data:
